// This file is generated by FlutterFire CLI.
// Run the following commands to regenerate after adding google-services.json:
//
//   dart pub global activate flutterfire_cli
//   flutterfire configure
//
// DO NOT edit this file manually.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError('Web is not configured. Run flutterfire configure.');
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbTWk36JufyiHYDDShhZQWuJzzqN0hicE',
    appId: '1:906093154226:android:1960feadf7e7540454deab',
    messagingSenderId: '906093154226',
    projectId: 'app-music-5cbc6',
    storageBucket: 'app-music-5cbc6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2sIaMW5hOtpT6F5Otp7Cpk455mwNYDws',
    appId: '1:906093154226:ios:9ee8310fec00f12754deab',
    messagingSenderId: '906093154226',
    projectId: 'app-music-5cbc6',
    storageBucket: 'app-music-5cbc6.firebasestorage.app',
    iosBundleId: 'com.example.flutterMusicCleanGetx',
  );

}